data:
  root: '/home/kunanont/BPBReid/datasets'
  sources: [ 'market1501' ]
  targets: [ 'market1501' ]
  height: 384
  width: 128
  transforms: [ 'rc', 're' ]
  workers: 0

model:
  name: 'bpbreid'
  load_weights: 'pretrained_models/bpbreid_market1501_hrnet32_10642.pth'
  load_config: False
  bpbreid:
    mask_filtering_training: False
    mask_filtering_testing: True
    learnable_attention_enabled: True
    backbone: 'hrnet32'
    test_embeddings: [ 'bn_foreg', 'parts' ]
    masks:
      dir: 'pifpaf_maskrcnn_filtering'
      preprocess: 'strp_6'
      parts_num: 6

test:
  evaluate: True
  batch_size: 8
  visrank: True
